ohmage-mongo:
    image: mongo:latest
    command: --smallfiles
ohmage-postgres:
    image: postgres:latest
ohmage-statics:
    image: smalldatalab/ohmage-statics:latest
    volumes: 
        - /var/www/ohmage-statics
ohmage-auth:
    image: smalldatalab/ohmage-auth-server:latest
    links:
        - ohmage-postgres:omh-postgres
        - ohmage-mongo:omh-mongo
        - ohmage-shim:ohmage-shim
    ports:
        - "8082:8082"
    environment:
        - application.url={BASE URL}/dsu/
        - google.clientId={GOOGLE CLIENT ID}
        - google.clientSecret={GOOGLE CLIENT SECRET}
        - server.port=8082
    volumes:
        - /var/log/ohmage/auth:/var/log/ohmage-auth
ohmage-resource:
    image: smalldatalab/ohmage-resource-server:latest
    links:
        - ohmage-postgres:omh-postgres
        - ohmage-mongo:omh-mongo
    ports:
        - "8083:8083"
    environment:
        - spring.dataSource.username=postgres
        - spring.dataSource.password=postgres
        - server.port=8083
    volumes:
        - /var/log/ohmage/resource:/var/log/ohmage-resource
ohmage-admin:
    image: smalldatalab/ohmage-admin-server:latest
    links:
        - ohmage-postgres:omh-postgres
        - ohmage-mongo:omh-mongo
    ports:
        - "3000:3000"
    environment:
        - APP_DB_DATABASE=admindashboard
        - APP_DB_USERNAME=postgres
        - APP_DB_PASSWORD=postgres
        - MANDRILL_USERNAME="user@example.com"
        - MANDRILL_PASSWORD="password"
    volumes:
        - /var/log/ohmage/admin:/sdl-admin-dashboard/log
ohmage-shim:
    image: smalldatalab/ohmage-shim-server:latest
    links:
        - ohmage-mongo:omh-mongo
    ports:
        - "8084:8084"
    environment:
        - logging.path=/var/log/ohmage-shim
        - openmhealth.shim.server.callbackUrlBase={BASE URL}/shims
        - openmhealth.shim.fitbit.clientId={FITBIT API KEY}
        - openmhealth.shim.fitbit.clientSecret={FITBIT API SECRET}
        - server.port=8084
    volumes:
        - /var/log/ohmage/shim:/var/log/ohmage-shim
ohmage-dpu:
    image: smalldatalab/ohmage-dpu-server:latest
    links:
        - ohmage-mongo:omh-mongo
        - ohmage-shim:ohmage-shim
    ports:
        - "8085:8085"
    volumes:
        - /var/log/ohmage/dpu:/var/log/ohmage-dpu
ohmage-nginx:
    image: smalldatalab/ohmage-nginx:latest
    links:
        - ohmage-auth:ohmage-auth
        - ohmage-resource:ohmage-resource
        - ohmage-admin:ohmage-admin
        - ohmage-shim:ohmage-shim
        - ohmage-dpu:ohmage-dpu
    ports:
        - "80:80"
    volumes:
        - /var/log/ohmage/nginx:/var/log/nginx
    volumes_from:
        - ohmage-statics
