# If you don't want the containers to start on machine boot, remove or update
#  the 'restart' flag for each container.

mongo:
    restart: unless-stopped
    image: mongo:3.2.1
    volumes:
        - mongodata:/data/db
    command: --smallfiles ## remove this line for production
postgres:
    restart: unless-stopped
    image: postgres:9.4.5
    volumes:
        - postgresdata:/var/lib/postgresql/data
auth:
    restart: unless-stopped
    image: smalldatalab/ohmage-auth-server:latest
    links:
        - postgres:omh-postgres
        - mongo:omh-mongo
        - shim:ohmage-shim
    environment:
        - application.url={BASE URL}/dsu/
        - server.port=8082
        # Uncomment next two lines if you want to enable users to login with a google accout
        #- google.clientId={GOOGLE CLIENT ID}
        #- google.clientSecret={GOOGLE CLIENT SECRET}
    # volumes:
        # Uncomment and update /path/to/logs' if you want local log files
        # - /path/to/logs/auth:/var/log/ohmage-auth
resource:
    restart: unless-stopped
    image: smalldatalab/ohmage-resource-server:latest
    links:
        - postgres:omh-postgres
        - mongo:omh-mongo
    environment:
        - spring.dataSource.username=postgres
        - spring.dataSource.password=postgres
        - server.port=8083
    # volumes:
        # Uncomment and update /path/to/logs' if you want local log files
        # - /path/to/logs/resource:/var/log/ohmage-resource
admin:
    restart: unless-stopped
    image: smalldatalab/ohmage-admin-server:latest
    links:
        - postgres:omh-postgres
        - mongo:omh-mongo
    environment:
        - APP_DB_DATABASE=admindashboard
        - APP_DB_USERNAME=postgres
        - APP_DB_PASSWORD=postgres
        - APP_DB_HOST=omh-postgres
        - APP_MONGO_HOST=omh-mongo
        - APP_MONGO_DATABASE=omh
        - MANDRILL_HOST=https://ohmage-omh.smalldata.io
        - MANDRILL_USERNAME="user@example.com"
        - MANDRILL_PASSWORD="password"
    # volumes:
        # Uncomment and update /path/to/logs' if you want local log files
        # - /path/to/logs/admin:/sdl-admin-dashboard/log
shim:
    restart: unless-stopped
    image: smalldatalab/ohmage-shim-server:latest
    links:
        - mongo:omh-mongo
    environment:
        - logging.path=/var/log/ohmage-shim
        - server.port=8084
        - openmhealth.shim.server.callbackUrlBase={BASE URL}/shims
        # Uncomment the shims that you will use, and supply clientId and clientSecret
        #- openmhealth.shim.fitbit.clientId={FITBIT API KEY}
        #- openmhealth.shim.fitbit.clientSecret={FITBIT API SECRET}
        #- openmhealth.shim.moves.clientId={MOVES API KEY}
        #- openmhealth.shim.moves.clientSecret={MOVES API SECRET}
    # volumes:
        # Uncomment and update '/path/to/logs' if you want local log files
        # - /path/to/logs/shim:/var/log/ohmage-shim
dpu:
    restart: unless-stopped
    image: smalldatalab/ohmage-dpu-server:latest
    links:
        - mongo:omh-mongo
        - shim:ohmage-shim
    # volumes:
        # Uncomment and update '/path/to/logs' if you want local log files
        # - /path/to/logs/dpu:/var/log/ohmage-dpu
nginx:
    restart: unless-stopped
    image: smalldatalab/ohmage-nginx:latest
    links:
        - auth:ohmage-auth
        - resource:ohmage-resource
        - admin:ohmage-admin
        - shim:ohmage-shim
        - dpu:ohmage-dpu
    ports:
        - "80:80"
    # volumes:
        # Uncomment and update '/path/to/logs' if you want local log files
        # - /path/to/logs/nginx:/var/log/nginx
